# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: mohammedrayan9064@gmail.com
author_name: Rayan9064
contract_name: nutri_contract
deployment_language: python
preset_name: starter
project_name: algo-contract

