# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: mohammedrayan9064@gmail.com
author_name: Rayan9064
preset_name: starter
project_name: integrate_contract

